package org.rcsb.common.jsonschema2pojo.rules;

import com.sun.codemodel.JDefinedClass;
import com.sun.codemodel.JDocCommentable;
import org.jsonschema2pojo.Annotator;
import org.jsonschema2pojo.GenerationConfig;
import org.jsonschema2pojo.SchemaStore;
import org.jsonschema2pojo.rules.Rule;
import org.jsonschema2pojo.rules.RuleFactory;

/**
 * Instance of a custom Required  Rules used for code generation.
 *
 * Created by Yana Valasatava on 8/9/18.
 */
public class CustomRequiredRuleFactory extends RuleFactory {

    /**
     * Create a new rule factory with the given generation config options.
     *
     * @param generationConfig
     *            The generation config options for type generation. These
     *            config options will influence the java code generated by rules
     *            created by this factory.
     * @param annotator
     *            the annotator used to mark up Java types with any annotations
     *            that are required to build JSON compatible types
     * @param schemaStore
     *            the object used by this factory to get and store schemas
     */
    public CustomRequiredRuleFactory(GenerationConfig generationConfig, Annotator annotator, SchemaStore schemaStore) {
        super(generationConfig, annotator, schemaStore);
    }

    public CustomRequiredRuleFactory() {
        super();
    }

    @Override
    public Rule<JDocCommentable, JDocCommentable> getRequiredRule() {
        return new CustomRequiredRule(this);
    }

    @Override
    public Rule<JDefinedClass, JDefinedClass> getRequiredArrayRule() {
        return new CustomRequiredArrayRule(this);
    }
}